#!/usr/bin/env python3
"""Copy named function definitions verbatim out of a product source file.

telegram_helpers.cpp cannot be compiled on its own: it includes ~50 Telegram
headers and touches Main::Session in 28 places. The handful of functions that
depend on nothing beyond their arguments are still worth executing, so the test
runner copies them - byte for byte, with #line pointing back at the original -
into a generated translation unit. Nothing here rewrites or paraphrases code:
if a requested signature is missing, duplicated, or no longer starts a
definition, extraction fails and the build stops. That is the whole point, a
stale copy must never be able to pass silently.

Usage:
  extract_functions.py --source FILE --output FILE
                       [--include HEADER]... [--system-include HEADER]...
                       SIGNATURE...
"""

import argparse
import os
import sys


def skip_to_end_of_body(text, start):
	"""Return the index just past the '}' closing the block opened at start."""
	depth = 0
	i = start
	n = len(text)
	while i < n:
		c = text[i]
		if c == "/" and i + 1 < n and text[i + 1] == "/":
			i = text.find("\n", i)
			if i < 0:
				return -1
			continue
		if c == "/" and i + 1 < n and text[i + 1] == "*":
			closed = text.find("*/", i + 2)
			if closed < 0:
				return -1
			i = closed + 2
			continue
		if c in "\"'":
			quote = c
			i += 1
			while i < n:
				if text[i] == "\\":
					i += 2
					continue
				if text[i] == quote:
					i += 1
					break
				i += 1
			continue
		if c == "{":
			depth += 1
		elif c == "}":
			depth -= 1
			if depth == 0:
				return i + 1
		i += 1
	return -1


def extract(text, signature, source):
	starts = []
	at = text.find(signature)
	while at >= 0:
		if at == 0 or text[at - 1] == "\n":
			starts.append(at)
		at = text.find(signature, at + 1)

	if not starts:
		sys.exit(f"{source}: no definition starts with {signature!r}")
	if len(starts) > 1:
		lines = ", ".join(str(text.count("\n", 0, s) + 1) for s in starts)
		sys.exit(f"{source}: {signature!r} starts several definitions (lines {lines})")

	start = starts[0]
	rest = text[start + len(signature):]
	if rest.lstrip()[:1] != "{":
		sys.exit(f"{source}: {signature!r} is not followed by a function body")

	brace = start + len(signature) + (len(rest) - len(rest.lstrip()))
	end = skip_to_end_of_body(text, brace)
	if end < 0:
		sys.exit(f"{source}: unbalanced braces in {signature!r}")

	return text.count("\n", 0, start) + 1, text[start:end]


def main():
	parser = argparse.ArgumentParser(add_help=True)
	parser.add_argument("--source", required=True)
	parser.add_argument("--output", required=True)
	parser.add_argument("--include", action="append", default=[])
	parser.add_argument("--system-include", action="append", default=[])
	parser.add_argument("signatures", nargs="+")
	args = parser.parse_args()

	source = os.path.abspath(args.source)
	with open(source, encoding="utf-8") as f:
		text = f.read()

	out = [f"// generated by extract_functions.py from {os.path.basename(source)}\n"]
	for header in args.include:
		out.append(f'#include "{header}"\n')
	if args.include and args.system_include:
		out.append("\n")
	for header in args.system_include:
		out.append(f"#include <{header}>\n")

	for signature in args.signatures:
		line, body = extract(text, signature, source)
		out.append(f'\n#line {line} "{source}"\n')
		out.append(body)
		out.append("\n")

	with open(args.output, "w", encoding="utf-8") as f:
		f.write("".join(out))

	print(f"copied {len(args.signatures)} function(s) from {os.path.basename(source)}")


if __name__ == "__main__":
	main()
